### PR TITLE
Add interactive LC plotter plotlc.py

### PR DESCRIPTION
**Pull request by emirkmo**
This is a simple lightcurve plotting script that would be nice to have inside of flows as an optional script. However, it needs pandas and mplcursors, as well as Qt5Agg backend. It's only for us to use when diagnosing template subtractions as it allows one to quickly plot a selection of files or a target and can click on the individual points to get the fileID#. To make it easy for those doing imagematch template subtraction, I think we should bundle it with flows.

We can leave it as an optional script that requires the user to get the additional required packages to run.

### CODE REVIEW

**Comment by rhandberg** [comment]
Could I get you to do run `flake8` on that code and clean up the worst errors it throws before we include it... There are some dependencies that are not used anyway and other minor stuff. You can see an example of the output here:
https://travis-ci.org/github/rhandberg/flows/jobs/725180138

**Comment by rhandberg** [comment]
Normally I use the convention of having any command-line scripts have a name like `run_<something>.py`, i.e. starting with "run_". Should we keep that convention? In which case you should rename the file to something like "run_plotlc.py"

**Comment by emirkmo** [comment]
I'll fix this up and change the name too. Good call

**Comment by rhandberg** [comment]
Also, (and I know this is a source of controversy!) the rest of the code uses TABS to indent, and not spaces...

**Comment by emirkmo** [comment]
Ok everything but spaces/tabs is basically fixed. I have all my editors set-up to use spaces so I really don't want to delve into that right now..

**Comment by emirkmo** [comment]
Change test to check 3.8 instead of 3.5, then let's go ahead and merge this.

**Pull request merged**
