### PR TITLE
Fix lcogt header

### PR DESCRIPTION
**Pull request by emirkmo**
This is PR is for merging the helper script to fix LCOGT headers output form image match.

### CODE REVIEW

**Comment by emirkmo** [comment]
I think I made these changes on the changes in PR:4, but it should merge without an issue after we merge that one. Whoops.

**Comment by rhandberg** [comment]
Would it not make sense to include this functionality into the ImageMatch wrapper we want to create?

**Comment by emirkmo** [comment]
I'm in favor of just adding this helper script as a tool for now, (it helps me getting others started with doing template subtraction for their flows supernovae. I can have them install imagematch and flows and they have all the scripts they need. I don't have to send anything else) then we can pull it into any sort of wrapper we create down the line. 

I guess I could also just bundle it with my fork of imagematch but it requires flows api calls, nothing from imagematch, so it made more sense here.

**Comment by emirkmo** [comment]
Closing until ImageMatch changes are reworked

**Pull request closed without merging**
